# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getinformation',
            old_name='Password',
            new_name='OnlineUserPassword',
        ),
        migrations.RemoveField(
            model_name='getinformation',
            name='ActiveMobileDeposite',
        ),
    ]
