# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rise', '0002_auto_20170721_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getinformation',
            old_name='RouttNumber',
            new_name='RoutNumber',
        ),
    ]
